<template>
	<div class="loadingio-spinner-reload-j7zqbkdehj">
		<div class="ldio-sjqmgw4mzmp">
			<div>
				<div></div>
				<div></div>
				<div></div>
			</div>
		</div>
	</div>
</template>

<style >
@keyframes ldio-sjqmgw4mzmp { 0% { transform: rotate(0) } 100% { transform: rotate(360deg); } }
.ldio-sjqmgw4mzmp > div {
	animation: ldio-sjqmgw4mzmp 1s infinite linear;
	transform-origin: 100px 100px;
}
.ldio-sjqmgw4mzmp > div div { position: absolute; }
.ldio-sjqmgw4mzmp > div div:nth-child(1), .ldio-sjqmgw4mzmp > div div:nth-child(2) {
	width: 164px;
	height: 164px;
	border: 24px solid;
	border-radius: 50%;
	border-color: transparent #e15b64 #e15b64 #e15b64;
	box-sizing: border-box;
	position: absolute;
	transform: rotate(45deg);
	transform-origin: 100px 100px;
}
.ldio-sjqmgw4mzmp > div div:nth-child(1) {
	transform: rotate(45deg) translate(18px, 18px);
}
.ldio-sjqmgw4mzmp > div div:nth-child(2) {
	transform: rotate(0deg) translate(18px, 18px);;
}
.ldio-sjqmgw4mzmp > div div:nth-child(3) {
	width: 0;
	height: 0;
	border: 24px solid;
	border-color: transparent transparent transparent #e15b64;
	transform: translate(100px, 6px);
}
.loadingio-spinner-reload-j7zqbkdehj {
	width: 200px;
	height: 200px;
	display: inline-block;
	overflow: hidden;
	background: #ffffff;
}
.ldio-sjqmgw4mzmp {
	width: 100%;
	height: 100%;
	position: relative;
	transform: translateZ(0) scale(1);
	backface-visibility: hidden;
	transform-origin: 0 0; /* see note above */
}
.ldio-sjqmgw4mzmp div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
